version: 2
jobs:
  build:
    docker:
      - image: node:boron
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm i -g yarn
      - run:
          name: Install Dependencies
          command: yarn --pure-lockfile
      - run:
          name: Test
          command: yarn test
